AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Codebuild Github User Story Builder

Parameters:
  ProjectName:
    Type: String
    Default: real-time-user-stories-codebuild
    Description: >-
      The name of the Codebuild project
  RepositoryLocation:
    Type: String
    Description: >-
      The HTTPS clone URL for the Github repository

Resources:
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:17.09.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref 'AWS::AccountId'
      ServiceRole: !Ref BuildProjectRole
      Source:
        Type: GITHUB
        Location: !Ref RepositoryLocation
      Triggers:
        Webhook: true

  BuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        !Join [ '-', [ !Ref ProjectName, !Ref 'AWS::Region'] ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName:
            !Join [ '-', [ !Ref ProjectName, !Ref 'AWS::Region'] ]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ec2:*
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ecr:*
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ecs:*
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:*
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - route53:*
                Resource:
                  - '*'
